version: "3"
services:
  web:
    image: menu-scan-order-api
    ports:
      - "8000:8000"
    links:
      - mysql
      - redis
  mysql:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
  redis:
    image: "redis:alpine"
